### ISSUE TITLE
selec画面でSETボタンを押下するとgame画面に戻る。game画面のブラックボックスに、選んでいるカードの内容が反映される 

### ISSUE THREAD

**Issue by TsukasaKashima** [TsukasaKashima/OFC-#14]
## 概要
掲題の通り
(Reduxを使用して実現する)

## 終了条件
プルリクエストがmergeされたら

## 見込み工数
7H

**Comment by azusa-ttt** [comment]
なるほど・・。
以下のような状態になるのが問題ということですね。
![image](https://user-images.githubusercontent.com/20539093/91306329-53f13600-e7e7-11ea-8f43-d2dfca2b4c07.png)

カードの置き換えによって、{type:undefined, number:undefind}のカードと置き換わってしまうと。

ならば、select画面に遷移する前にselectedCardsを空配列にしてしまうのはどうですかね？
つまり、「自由に選ぶ」のボタンを押下したときに、
`props.setSelectedCards([])`
としてやるということです。
いかがでしょうか。

**Comment by TsukasaKashima** [comment]
ありがとうございます！
いただいた1行のみで解決することができました・・！
（どうしても深く考えてしまって解決に至らないことが多いです。。）

それでは別の修正点も対応いたします！
引き続きよろしくお願いいたします！

**Comment by azusa-ttt** [comment]
あ！プルリクで質問いただいてたのにこっちに書いちゃってました。すみません。。

引き続きよろしくお願いします。
